spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    timeout: 2000
    max-redirects: 8
    pool:
     maxActive: 8
     maxWait: -1
     maxIdle: 8
     minIdle: 0
  cache:
    prefix: ccs
    default-expire: 3600