spring:
  profiles:
    active: redis
  application:
    name: eureka-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useUnicode=true&&characterEncoding=UTF-8
    username: root
    password: root
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT1FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
  cluster:
    redis:
       host: 127.0.0.1
       port: 6379
       password:
       masterName: cluster6379
       maxTotal: 200
       maxIdle: 50
       numTestsPerEvictionRun: 1024
       maxWaitMillis: 1500
       blockWhenExhausted: false
       type: singleton
       expire: 10
    cache:
       prefix: ccs
  rabbitmq:
      host: 192.168.65.128
      username: guest
      password: guest
      virtual-host: /
server:
  port: 7888
eureka:
 client:
   service-url:
     defaultZone : http://localhost:8088/eureka
logging:
  level:
    com.midea : debug

mybatis-plus:
  global-config:
    db-column-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
  mapper-locations: classpath*:mappers/*.xml

#mybatis:
  #实体类所做包
#  type-aliases-package: com.midea.model
  #mapper.xml所在位置
 # mapper-locations: classpath:mappers/*.xml

swagger:
    enabled: true