server:
  port: 8081

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          #开启小写验证，默认feign根据服务名查找都是用的全大写
          lowerCaseServiceId: true
      routes:
        - id: eureka-client
          uri: lb://eureka-client
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=1
            - RequestTime=true
        - id: service-ribbon
          uri: lb://service-ribbon
          predicates:
            - Path=/ribbon/**
          filters:
            - StripPrefix=1
            - RequestTime=true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8088/eureka
